### ISSUE TITLE
Swift package product 'NIOFoundationCompat' is linked as a static library 

### ISSUE THREAD

**Issue by mikeumus** [open-telemetry/opentelemetry-swift#111]
```
Swift package product 'NIOFoundationCompat' is linked as a static library by 'MyProjectName' and 
'OpenTelemetryProtocolExporter'. This will result in duplication of library code.
```
Seen here as a real bug with XCode 12:
https://stackoverflow.com/questions/64129750/swift-package-manager-unexpected-duplicate-tasks-target-apptests-project-app

Anybody else experiencing this with XCode?
Any solutions available yet?
Maybe the latest XCode beta doesn't have this issue? 

<img width="274" alt="Screen Shot 2021-02-20 at 4 12 10 AM" src="https://user-images.githubusercontent.com/57934/108590489-d9d2e180-7331-11eb-9b81-e80575027db8.png">

**Comment by nachoBonafonte** [comment]
If you are manually adding NIO to the project, the best solution imho is avoid linking NIO libraries in the project, since they are already contained in OpenTelemetryProtocolExporter, you will need to use the same version of NIO though.

But if both NIO libraries come as dependencies of other libraries, I think the best solution is creating an intermediate package that includes both packages.

Maybe someone has some better options.

**Comment by mikeumus** [comment]
@nachoBonafonte This also happens when just importing the SDK and API. 😐

**Comment by nachoBonafonte** [comment]
Yes, you should only add the dependency to the SDK (or the exporter if it is the case), because SDK includes API itself, and Xcode links them both statically. But after that you can import both libraries in your code: 
```
import OpenTelemetryApi
import OpenTelemetrySdk
```

I think Xcode 12.5 (now in beta) will solve this issue automatically and will allow to add both to dependencies: 
> Xcode 12.5 Beta 3 Release Notes:
The Swift Package Manager now builds package products and targets as dynamic frameworks automatically, if doing so avoids duplication of library code at runtime. (59931771) (FB7608638)

**Comment by nachoBonafonte** [comment]
Closing it after 15 without more comments, will reopen if receive more comments
