### ISSUE TITLE
Compiling for iOS 9.0, but module 'JaegerExporter' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by cawezh** [open-telemetry/opentelemetry-swift#238]
Compiling for iOS 9.0, but module 'JaegerExporter' has a minimum deployment target of iOS 11.0

**Comment by nachoBonafonte** [comment]
Hi cawezh,
It is not possible to build for iOS 9.0, one of the dependencies of the project is `os.activity` framework, which is used for context handling, and is only available starting with iOS 10.0. 

The project could probably build with iOS 10, but would be needed an old Xcode version (11 or below) for testing and debugging any issue, and probably that Xcode version wont work on macOS 12 Mavericks, which makes near term maintenance a bit difficult.

**Comment by cawezh** [comment]
@nachoBonafonte Thanks, can you support dynamic libraries?

**Comment by cawezh** [comment]
@nachoBonafonte Thanks

**Comment by lzctxwd** [comment]
@nachoBonafonte I have encountered the same problem. I have a project that needs to be run on ios8. For some reasons, the deploymentinfo of this project cannot be upgraded. Is there any way for me to reference this project

**Comment by nachoBonafonte** [comment]
No, sorry, as said previously is not going to be officially supported. Minimum version is iOS 11 because is the minimum version we can maintain with current available development tools, and the tools needed for supporting something older will probably have incompatible swift version support. Also context handling for iOS < 10 would need a totally different implementation.

If you really need to support it you will have to fork the project and add the support yourself. Probably the bigger issue will be replacing the logic for context handling, the current API already has a way to replace the active ContextManager, but for iOS 8 will need a totally different approach (probably no easy way to automatically handle it for the user, so API will need to be modified everywhere)
