### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by valiaga** [open-telemetry/opentelemetry-swift#278]
HI,
Do you have any plan to support Cocoapods?

Since I would like to use OpenTelemetry-Swift on my project but we don't have support for Swift Package Manager , I tried to migrate the current version to cocoapods, but due to dependencies like atomic-Swift(another library only in SPM), and others check of our CI/CD implementation for support SPM  this unfortunately failed. 

Many projects still use only cocoapods or carthage, as dependency managers, adding support for other managers would potentially open OpenTelemetry-Swift to many more users.

Please let me know what you think about adding Cocoapods support to OpenTelemetry-Swift or if you plan to add other dependency managers in the future.

**Comment by shelefg** [comment]
FWIW I was able to consume the Otel-swift libraries I needed with cocoapods by creating podspecs for `swift-atomics` on a [private Cocoapods Specs repo](https://guides.cocoapods.org/making/private-cocoapods.html).

I created gists for the podspecs. I had to create two because I couldn't find a way to make cocoapods create two modules in one pod, which swift-atomics requires:
[SwiftAtomics](https://gist.github.com/shelefg/db6fe1fb29ed1a280327ff0e6e8ef677) 
[SwiftAtomicShims](https://gist.github.com/shelefg/57a4b842de1d1007641d9ce1876de4bc)

**Comment by lswank** [comment]
This makes sense to do if Cocoa Pods and Swift Package Manager don't play well with each other. I've used them together in several projects, but I may just have been lucky. Does anyone have a good example of a minimal project where they don't work together?

**Comment by Nanodroop** [comment]
I have the same problem. there is no way to use packages in the project, as they are incompatible with pods in this particular case. if there is any solution to support Cocoapods, please let me know

**Comment by bryce-b** [comment]
collapsing this issue into #453
