### ISSUE TITLE
LogRecord is out of Spec, expand log body field to type Any

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#462]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body
The log data body field should take any type, but the swift implementation only allows strings

**Comment by jCharv** [comment]
Hey Bryce, I've been looking into this for a bit because we'll need LogRecords to accept binary data. 

I've tried a very simple solution where I extended AttributeValue with a Data value, and then used AttributeValue as a type for the LogRecord.body. This enables sending binary data both in LogRecord.attributes and in LogRecord.body.

Am I correct to assume that this approach is not suitable for a PR, because this exposes Data value as an Attribute for all other signals as well? I'm not quite sure that this would be a bug or a feature.

**Comment by bryce-b** [comment]
Let's add a subclass of `AttributeValue` to use for log signals that allows `Any` data type.
