### ISSUE TITLE
Clear all data in UserDefault when init OpenTelemetry

### ISSUE THREAD

**Issue by Chung14011998** [open-telemetry/opentelemetry-swift#586]
OpenTelemetry.registerTracerProvider(tracerProvider: TracerProviderBuilder()
             .add(spanProcessor: SimpleSpanProcessor(spanExporter: OtlpHttpTraceExporter(endpoint: endpoint, useSession: session)))
             .with(resource: resource)
             .build())

After I init openTelemetry, all data in UserDefault is removed. How to keep data when init it.
(Only get this error when ios >= 16)

**Comment by bryce-b** [comment]
Hi @Chung14011998, 
We took a look, and we are not using 'UserDefaults'. Perhaps your issue is coming from somewhere else?

**Comment by Chung14011998** [comment]
@bryce-b I have printed out UserDefaults before and after initializing OpenTelemetry. Before initialization, the data was still full, after initialization I printed it out and all the data was deleted. I see a lot of values ​​written to UserDefaults with the prefix WebKitxxx

**Comment by bryce-b** [comment]
Hi @Chung14011998,
 I added a breakpoint for `UserDefaults.standard()` and ran this code, and didn't find anything calling it. You might try to do the same and identify where the issue is coming from.

**Comment by Chung14011998** [comment]
@bryce-b b
print("UserDefaults Before Init \(UserDefaults.standard.dictionaryRepresentation())")
OpenTelemetry.registerTracerProvider(tracerProvider: TracerProviderBuilder()
         .add(spanProcessor: SimpleSpanProcessor(spanExporter: OtlpHttpTraceExporter(endpoint: endpoint, useSession: session)))
         .with(resource: resource)
         .build())
print("UserDefaults After Init \(UserDefaults.standard.dictionaryRepresentation())")

Some values after init OpenTelemetry are removed. I tried to get all the keys and values ​​to see the problem.

**Comment by mattbroussard** [comment]
I'm seeing this behavior on iOS 17 as well.

**Comment by mattbroussard** [comment]
Have looked into this a bit and determined that at least in our app's case, the issue seems to stem from our usage of `URLSessionInstrumentation` -- if I comment out the initialization of that the issue goes away. @Chung14011998 are you also using that? It's not shown in your example.

The `WebKit*` UserDefaults keys also seem to show up for me right after `URLSessionInstrumentation` is inited.

On iOS, UserDefaults persists to a plist file in the app's sandbox container under Library/Preferences -- I wonder if in iOS 17 Apple has made an internal change that causes this file persistence to utilize URLSession in some way that `URLSessionInstrumentation` interferes with?

We had seen behavior where data already in UserDefaults from previous app runs could be read but no changes could be persisted to disk so wondered if maybe opentelemetry-swift was doing something to make the container or some folder within it readonly or otherwise prevent writing changes. Our app is deployed in an enterprise environment with some [Managed App Configuration](https://blog.eidinger.info/all-you-need-to-know-about-managed-app-configuration) fields via MDM and those also seem to be unreadable -- not sure when/where Apple's internal implementation writes those from.

@rob0rt and I intend to investigate further, will comment if we discover anything useful.

**Comment by mattbroussard** [comment]
I tried checking for non-HTTP(S) (e.g. `file`) requests in `shouldInstrument` and it seems like they don't even get there if they're happening at all.

**Comment by bryce-b** [comment]
This seems like a broader issue occurring with iOS 17 : 
https://forums.developer.apple.com/forums/thread/741719

**Comment by rob0rt** [comment]
@bryce-b there might be other issues other people are experiencing on iOS 17, but concretely and reproducibly: the URLSessionInstrumentation in this library breaks UserDefaults persistence on iOS/ iPadOS 17. I have not identified the specific mechanics at play that cause the issue but have been to repeatedly verify that the removal of the URLSessionInstrumentation initialization from my app fixes the issue (or vice-versa causes it when re-adding). This reproduces on a clean iOS project. My team spent an entire work day collectively debugging this as it caused a production issue.

I presume there's something internal that has changed with the implementation of UserDefaults on iOS 17 that perhaps interferes negatively with the extensive swizzling the instrumentation library does. I've unfortunately not been able to debug it extensively to identify it.

**Comment by rob0rt** [comment]
I don't think this should be closed; Something in the `URLSessionInstrumentation` implementation seems to cause this since it exclusively happens when that library is initialized. 

I've tested in a blank project and not repro'd but it does repro consistently in my production project. I would assume that it interferes negatively with some other library (Firebase, maybe?) but none of our other libraries cause this on its own, so I would struggle to say it's not a problem with this library's instrumentation.
